-- Test query to check all cache tables and see what's actually stored
-- Run this in Snowflake to diagnose cache issues

USE DATABASE TELCO_NETWORK_OPTIMIZATION_PROD;
USE SCHEMA AI_CACHE;

-- Check each cache table
SELECT 'MAIN_PAGE_CACHE' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM MAIN_PAGE_CACHE
UNION ALL
SELECT 'AI_INSIGHTS_CACHE', COUNT(*) FROM AI_INSIGHTS_CACHE
UNION ALL  
SELECT 'CUSTOMER_PROFILE_CACHE', COUNT(*) FROM CUSTOMER_PROFILE_CACHE
UNION ALL
SELECT 'EXECUTIVE_SUMMARY_CACHE', COUNT(*) FROM EXECUTIVE_SUMMARY_CACHE
UNION ALL
SELECT 'PREDICTIVE_ANALYTICS_CACHE', COUNT(*) FROM PREDICTIVE_ANALYTICS_CACHE;

-- View all cached reports with details
SELECT * FROM ALL_CACHED_REPORTS ORDER BY CREATED_AT DESC LIMIT 50;

-- View cache statistics
SELECT * FROM CACHE_STATISTICS;
